# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

# Configurações adicionais do analisador
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
  
  # Configurações de linguagem
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  # Regras customizadas para melhorar qualidade do código
  rules:
    # Estilo e formatação
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    
    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_collection_literals: true
    prefer_spread_collections: true
    
    # Legibilidade e manutenibilidade
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_redundant_argument_values: true
    avoid_returning_null_for_void: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_null_aware_operators: true
    
    # Segurança
    close_sinks: true
    cancel_subscriptions: true
    
    # Flutter específico
    use_key_in_widget_constructors: true
    prefer_const_constructors_in_immutables: true
    sized_box_for_whitespace: true
    
    # Evitar problemas comuns
    avoid_print: false  # Permitido para debug durante desenvolvimento
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
